// <copyright file="QMakeBuilder.cs" company="Mark Final">
//  Opus package
// </copyright>
// <summary>QMakeBuilder package</summary>
// <author>Mark Final</author>

[assembly: Opus.Core.DeclareBuilder("QMake", typeof(QMakeBuilder.QMakeBuilder))]

// Automatically generated by Opus v0.20
namespace QMakeBuilder
{
}
