// Automatically generated by Opus v0.00
namespace Test11
{
    // Define module classes here
    class CrossPlatformApplication : C.Application
    {
        public CrossPlatformApplication()
        {
            var sourceDir = this.PackageLocation.SubDirectory("source");
            this.commonSourceFile.Include(sourceDir, "main.c");
            var winDir = sourceDir.SubDirectory("win");
            var unixDir = sourceDir.SubDirectory("unix");
            var osxDir = sourceDir.SubDirectory("osx");
            this.winSourceFile.Include(winDir, "win.c");
            this.unixSourceFile.Include(unixDir, "unix.c");
            this.osxSourceFile.Include(osxDir, "osx.c");
        }

        [Opus.Core.SourceFiles]
        C.ObjectFile commonSourceFile = new C.ObjectFile();

        [Opus.Core.SourceFiles(Platform=Opus.Core.EPlatform.Windows)]
        C.ObjectFile winSourceFile = new C.ObjectFile();

        [Opus.Core.SourceFiles(Platform=Opus.Core.EPlatform.Unix)]
        C.ObjectFile unixSourceFile = new C.ObjectFile();
        
        [Opus.Core.SourceFiles(Platform=Opus.Core.EPlatform.OSX)]
        C.ObjectFile osxSourceFile = new C.ObjectFile();

        [Opus.Core.DependentModules(Platform = Opus.Core.EPlatform.Windows, ToolsetTypes = new[] { typeof(VisualC.Toolset) })]
        Opus.Core.TypeArray WinVCDependents = new Opus.Core.TypeArray(typeof(WindowsSDK.WindowsSDK));

        [C.RequiredLibraries(Platform = Opus.Core.EPlatform.Windows, ToolsetTypes = new[] { typeof(VisualC.Toolset) })]
        Opus.Core.StringArray WinVCLibraries = new Opus.Core.StringArray("KERNEL32.lib");
    }
}
