// <copyright file="PreExecute.cs" company="Mark Final">
//  Opus package
// </copyright>
// <summary>QMakeBuilder package</summary>
// <author>Mark Final</author>
namespace QMakeBuilder
{
    public sealed partial class QMakeBuilder2
    {
        public void PreExecute()
        {
            Opus.Core.Log.MessageAll("PreExecute for QMakeBuilder");

            var mainPackage = Opus.Core.State.PackageInfo[0];
            string priFileName = "EmptyConfig.pri";
            string rootDirectory = mainPackage.BuildDirectory;
            string priFilePath = System.IO.Path.Combine(rootDirectory, priFileName);

            System.IO.Directory.CreateDirectory(rootDirectory);
            using (System.IO.TextWriter proFileWriter = new System.IO.StreamWriter(priFilePath))
            {
                proFileWriter.WriteLine("# -- Generated by Opus --");
                proFileWriter.WriteLine("TEMPLATE=");
                proFileWriter.WriteLine("# CONFIG cannot be completely emptied");
                proFileWriter.WriteLine("CONFIG-=qt");
                proFileWriter.WriteLine("CONFIG-=lex");
                proFileWriter.WriteLine("CONFIG-=yacc");
                proFileWriter.WriteLine("CONFIG-=warn_on");
                proFileWriter.WriteLine("CONFIG-=uic");
                proFileWriter.WriteLine("CONFIG-=resources");
                proFileWriter.WriteLine("CONFIG-=rtti_off");
                proFileWriter.WriteLine("CONFIG-=exceptions_off");
                proFileWriter.WriteLine("CONFIG-=stl_off");
                proFileWriter.WriteLine("CONFIG-=incremental_off");
                proFileWriter.WriteLine("CONFIG-=thread_off");
                proFileWriter.WriteLine("CONFIG-=windows");
                proFileWriter.WriteLine("CONFIG-=warn_on");
                proFileWriter.WriteLine("CONFIG-=incremental");
                proFileWriter.WriteLine("CONFIG-=flat");
                proFileWriter.WriteLine("CONFIG-=link_prl");
                proFileWriter.WriteLine("CONFIG-=precompile_header");
                proFileWriter.WriteLine("CONFIG-=autogen_precompile_source");
                proFileWriter.WriteLine("CONFIG-=copy_dir_files");
                proFileWriter.WriteLine("CONFIG-=embed_manifest_dll");
                proFileWriter.WriteLine("CONFIG-=embed_manifest_exe");
                proFileWriter.WriteLine("CONFIG-=shared");
                proFileWriter.WriteLine("CONFIG-=stl");
                proFileWriter.WriteLine("CONFIG-=exceptions");
                proFileWriter.WriteLine("CONFIG-=rtti");
                proFileWriter.WriteLine("CONFIG-=mmx");
                proFileWriter.WriteLine("CONFIG-=3dnow");
                proFileWriter.WriteLine("CONFIG-=sse");
                proFileWriter.WriteLine("CONFIG-=sse2");
                proFileWriter.WriteLine("CONFIG-=incredibuild_xge");
                proFileWriter.WriteLine("CONFIG-=console");
                proFileWriter.WriteLine("QT=");
                proFileWriter.WriteLine("DESTDIR=");
                proFileWriter.WriteLine("DEFINES=");
                proFileWriter.WriteLine("RC_FILE=");
                proFileWriter.WriteLine("QMAKE_COMPILER_DEFINES=");
                proFileWriter.WriteLine("QMAKE_CFLAGS=");
                proFileWriter.WriteLine("QMAKE_CFLAGS_DEBUG=");
                proFileWriter.WriteLine("QMAKE_CFLAGS_RELEASE=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS_DEBUG=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS_RELEASE=");
                proFileWriter.WriteLine("QMAKE_LFLAGS=");
                proFileWriter.WriteLine("QMAKE_LFLAGS_DEBUG=");
                proFileWriter.WriteLine("QMAKE_LFLAGS_RELEASE=");
            }

            this.EmptyConfigPriPath = priFilePath;
        }
    }

    public sealed partial class QMakeBuilder
    {
        public void PreExecute()
        {
            Opus.Core.Log.DebugMessage("PreExecute for QMakeBuilder");

            // Disable Qt setup
            Opus.Core.PackageInformation mainPackage = Opus.Core.State.PackageInfo[0];
            string fileName = "DisableQt.pri";
            string rootDirectory = mainPackage.BuildDirectory;
            string disableQtPriPathName = System.IO.Path.Combine(rootDirectory, fileName);

            System.IO.Directory.CreateDirectory(rootDirectory);
            using (System.IO.TextWriter proFileWriter = new System.IO.StreamWriter(disableQtPriPathName))
            {
                proFileWriter.WriteLine("# -- Generated by Opus --");
                proFileWriter.WriteLine("# Disable standard Qt configurations");
                proFileWriter.WriteLine("CONFIG -= qt mmx 3dnow sse sse2 sse3 ssse3 sse4_1 sse4_2 avx iwmmxt thread");
                proFileWriter.WriteLine("CONFIG += moc");
                proFileWriter.WriteLine("QT -= core gui");
                proFileWriter.WriteLine("QMAKE_LIBS_QT_ENTRY=");
                proFileWriter.WriteLine("QMAKE_CFLAGS=");
                proFileWriter.WriteLine("QMAKE_CFLAGS_WARN_ON=");
                proFileWriter.WriteLine("QMAKE_CFLAGS_DEBUG=");
                proFileWriter.WriteLine("QMAKE_CFLAGS_MT_DBG=");
                proFileWriter.WriteLine("QMAKE_CFLAGS_MT_DLLDBG=");
                proFileWriter.WriteLine("QMAKE_CFLAGS_THREAD=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS_WARN_ON=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS_WARN_OFF=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS_RELEASE=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS_DEBUG=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS_MT_DLLDBG=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS_MT_DLLDBG=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS_STL_ON=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS_STL_OFF=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS_RTTI_ON=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS_RTTI_OFF=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS_EXCEPTIONS_ON=");
                proFileWriter.WriteLine("QMAKE_CXXFLAGS_EXCEPTIONS_OFF=");
                proFileWriter.WriteLine("QMAKE_INCDIR=");
                proFileWriter.WriteLine("QMAKE_INCDIR_QT=");
                //proFileWriter.WriteLine("QMAKESPEC=");
                proFileWriter.WriteLine("DEFINES=");
                proFileWriter.WriteLine("INCLUDEPATH=");
                proFileWriter.WriteLine("mmx:DEFINES=");
                proFileWriter.WriteLine("3dnow:DEFINES=");
                proFileWriter.WriteLine("sse:DEFINES=");
                proFileWriter.WriteLine("sse2:DEFINES=");
                proFileWriter.WriteLine("sse3:DEFINES=");
                proFileWriter.WriteLine("ssse3:DEFINES=");
                proFileWriter.WriteLine("sse4_1:DEFINES=");
                proFileWriter.WriteLine("sse4_2:DEFINES=");
                proFileWriter.WriteLine("avx:DEFINES=");
                proFileWriter.WriteLine("iwmmxt:DEFINES=");
                proFileWriter.WriteLine("QMAKE_PRL_DEFINES=");
                proFileWriter.WriteLine("QMAKE_LFLAGS=");
                proFileWriter.WriteLine("QMAKE_LFLAGS_DEBUG=");
                proFileWriter.WriteLine("QMAKE_INCDIR=");
                proFileWriter.WriteLine("QMAKE_INCDIR_QT=");
                proFileWriter.WriteLine("QMAKE_LIBDIR_QT=");
                proFileWriter.WriteLine("#QMAKE_RUN_CC=$(CC) -c -Fo$obj $src");
                proFileWriter.WriteLine("#QMAKE_RUN_CC_IMP=$(CC) -c -Fo$@ $<");
                proFileWriter.WriteLine("#QMAKE_RUN_CC_IMP_BATCH=$(CC) -c -Fo$@ @<<");
                proFileWriter.WriteLine("#QMAKE_RUN_CXX=$(CXX) -c -Fo$obj $src");
                proFileWriter.WriteLine("#QMAKE_RUN_CXX_IMP=$(CXX) -c -Fo$@ $<");
                proFileWriter.WriteLine("#QMAKE_RUN_CXX_IMP_BATCH=$(CXX) -c -Fo$@ @<<");
                proFileWriter.WriteLine("QMAKE_LFLAGS_CONSOLE=");
                proFileWriter.WriteLine("QMAKE_LFLAGS_WINDOWS=");
            }
            this.DisableQtPriPathName = disableQtPriPathName;
        }
    }
}
