// Automatically generated by Opus v0.50
namespace Test17
{
    public class Application : C.Application
    {
        public class SourceFiles : C.ObjectFileCollection
        {
            public SourceFiles()
            {
                this.Include(this, "source", "*.c");
            }
        }

        [Opus.Core.SourceFiles]
        SourceFiles source = new SourceFiles();

        [Opus.Core.DependentModules]
        Opus.Core.TypeArray dependents = new Opus.Core.TypeArray(
            typeof(Test16.StaticLibrary2)
            );

        [Opus.Core.DependentModules(Platform=Opus.Core.EPlatform.Windows)]
        Opus.Core.TypeArray winDependents = new Opus.Core.TypeArray(
            typeof(WindowsSDK.WindowsSDK)
            );
    }
}
