// Automatically generated by Opus v0.00
namespace Test7
{
    // Define module classes here
    class ExplicitDynamicLibrary : C.DynamicLibrary
    {
        private const string WinVCTarget = "win.*-.*-visualc";

        public ExplicitDynamicLibrary()
        {
            this.sourceFile.UpdateOptions += SetIncludePaths;
        }

        private static void SetIncludePaths(Opus.Core.IModule module, Opus.Core.Target target)
        {
            C.ICCompilerOptions compilerOptions = module.Options as C.ICCompilerOptions;
            compilerOptions.IncludePaths.Add(Opus.Core.State.PackageInfo["Test7"], @"include");
        }

        [Opus.Core.SourceFiles]
        C.ObjectFile sourceFile = new C.ObjectFile("source", "dynamiclibrary.c");

        [Opus.Core.DependentModules(WinVCTarget)]
        Opus.Core.TypeArray winVCDependents = new Opus.Core.TypeArray(
            typeof(WindowsSDK.WindowsSDK)
        );

        [C.RequiredLibraries(WinVCTarget)]
        Opus.Core.StringArray libraries = new Opus.Core.StringArray(
            "KERNEL32.lib"
        );
    }
}
