// Automatically generated by Opus v0.20
namespace WPFTest
{
    // Define module classes here
    class WPFExecutable :
        CSharp.WindowsExecutable
    {
        public
        WPFExecutable()
        {
            var sourceDir = this.PackageLocation.SubDirectory("source");
            this.applicationDefinition = Bam.Core.FileLocation.Get(sourceDir, "App.xaml");
            this.page = Bam.Core.FileLocation.Get(sourceDir, "MainWindow.xaml");

            this.UpdateOptions += new Bam.Core.UpdateOptionCollectionDelegate(WPFExecutable_UpdateOptions);
        }

        void
        WPFExecutable_UpdateOptions(
            Bam.Core.IModule module,
            Bam.Core.Target target)
        {
            var options = module.Options as CSharp.IOptions;
            options.References.Add("System.dll");
            options.References.Add("System.Data.dll");
            options.References.Add("System.Xaml.dll");
            options.References.Add("WindowsBase.dll");
            options.References.Add("PresentationCore.dll");
            options.References.Add("PresentationFramework.dll");
        }

        [CSharp.ApplicationDefinition]
        Bam.Core.Location applicationDefinition;

        [CSharp.Pages]
        Bam.Core.Location page;
    }
}
