[assembly:Opus.Core.GlobalOptionCollectionOverride(typeof(Test.OptionOverride))]

// Automatically generated by Opus v0.00
namespace Test
{
    class OptionOverride : Opus.Core.IGlobalOptionCollectionOverride
    {
        public void OverrideOptions(Opus.Core.BaseOptionCollection optionCollection, Opus.Core.Target target)
        {
            if (optionCollection is C.ICCompilerOptions)
            {
                var compilerOptions = optionCollection as C.ICCompilerOptions;
                compilerOptions.Defines.Add("GLOBALOVERRIDE");
            }

            if (optionCollection is C.ICxxCompilerOptions)
            {
                var compilerOptions = optionCollection as C.ICxxCompilerOptions;
                compilerOptions.ExceptionHandler = C.Cxx.EExceptionHandler.Asynchronous;
            }

            // TODO: pdb support
#if false
            if (optionCollection is VisualCCommon.LinkerOptionCollection)
            {
                var linkerOptions = optionCollection as VisualCCommon.LinkerOptionCollection;
                linkerOptions.ProgamDatabaseDirectoryPath = System.IO.Path.Combine(Opus.Core.State.BuildRoot, "symbols");
            }
#endif
        }
    }

    sealed class CompileSingleCFile : C.ObjectFile
    {
        public CompileSingleCFile()
        {
            var sourceDir = this.PackageLocation.SubDirectory("source");
            this.Include(sourceDir, "main.c");
        }
    }

    sealed class CompileSingleCFileWithCustomOptions : C.ObjectFile
    {
        public CompileSingleCFileWithCustomOptions()
        {
            var sourceDir = this.PackageLocation.SubDirectory("source");
            this.Include(sourceDir, "main.c");
            this.UpdateOptions += UpdateCompilerOptions;
        }

        private static void UpdateCompilerOptions(Opus.Core.IModule module, Opus.Core.Target target)
        {
            var compilerOptions = module.Options as C.ICCompilerOptions;

            compilerOptions.ShowIncludes = true;

            if (target.HasToolsetType(typeof(Mingw.Toolset)))
            {
                Opus.Core.Log.MessageAll("Toolset for mingw in use");

                if (target.HasConfiguration(Opus.Core.EConfiguration.Debug))
                {
                    compilerOptions.Optimization = C.EOptimization.Custom;
                }

                compilerOptions.AdditionalOptions = "-Wall";

                var mingwCompilerOptions = compilerOptions as MingwCommon.ICCompilerOptions;
                mingwCompilerOptions.InlineFunctions = true;
            }
            else if (target.HasToolsetType(typeof(VisualC.Toolset)))
            {
                Opus.Core.Log.MessageAll("Toolset for visualc in use");

                compilerOptions.Optimization = C.EOptimization.Custom;
                compilerOptions.CustomOptimization = "-Ox";
                compilerOptions.AdditionalOptions = "-openmp";

                compilerOptions.DebugSymbols = true;
                var vcCompilerOptions = compilerOptions as VisualCCommon.ICCompilerOptions;
                vcCompilerOptions.DebugType = VisualCCommon.EDebugType.Embedded;
                vcCompilerOptions.BasicRuntimeChecks = VisualCCommon.EBasicRuntimeChecks.None;
                vcCompilerOptions.SmallerTypeConversionRuntimeCheck = false;
            }
            else if (target.HasToolsetType(typeof(Gcc.Toolset)))
            {
                Opus.Core.Log.MessageAll("Toolset for gcc in use");

                compilerOptions.AdditionalOptions = "-Wall";

                var gccCompilerOptions = compilerOptions as GccCommon.ICCompilerOptions;
                gccCompilerOptions.PositionIndependentCode = true;
            }
            else if (target.HasToolsetType(typeof(LLVMGcc.Toolset)))
            {
                Opus.Core.Log.MessageAll("Toolset for llvm-gcc in use");

                compilerOptions.AdditionalOptions = "-Wall";

                GccCommon.ICCompilerOptions gccCompilerOptions = compilerOptions as GccCommon.ICCompilerOptions;
                gccCompilerOptions.PositionIndependentCode = true;
            }
            else if (target.HasToolsetType(typeof(Clang.Toolset)))
            {
                Opus.Core.Log.MessageAll("Toolset for clang in use");

                compilerOptions.AdditionalOptions = "-Wall";

                var clangCompilerOptions = compilerOptions as ClangCommon.ICCompilerOptions;
                clangCompilerOptions.PositionIndependentCode = true;
            }
            else
            {
                Opus.Core.Log.MessageAll("Unrecognized toolset, '{0}'", target.ToolsetName('='));
            }
        }
    }

    sealed class CompileCSourceCollection : C.ObjectFileCollection
    {
        public CompileCSourceCollection()
        {
            var sourceDir = this.PackageLocation.SubDirectory("source");
            this.Include(sourceDir, "*.c");
        }
    }

    sealed class CompileSingleCppFile : C.Cxx.ObjectFile
    {
        public CompileSingleCppFile()
        {
            var sourceDir = this.PackageLocation.SubDirectory("source");
            this.Include(sourceDir, "main.c");
        }
    }

    sealed class CompileCppSourceCollection : C.Cxx.ObjectFileCollection
    {
        public CompileCppSourceCollection()
        {
            var sourceDir = this.PackageLocation.SubDirectory("source");
            this.Include(sourceDir, "*.c");
        }
    }

    sealed class CompileCSourceCollectionWithCustomOptions : C.ObjectFileCollection
    {
        public CompileCSourceCollectionWithCustomOptions()
        {
            var sourceDir = this.PackageLocation.SubDirectory("source");
            this.Include(sourceDir, "*.c");

            this.UpdateOptions += OverrideOptionCollection;

            // override the options on one specific file
            this.RegisterUpdateOptions(new Opus.Core.UpdateOptionCollectionDelegateArray(mainObjFile_UpdateOptions),
                                       sourceDir, "main.c");
        }

        void mainObjFile_UpdateOptions(Opus.Core.IModule module, Opus.Core.Target target)
        {
            var compilerOptions = module.Options as C.ICCompilerOptions;
            compilerOptions.Defines.Add("DEFINE_FOR_MAIN_ONLY");
        }

        public void OverrideOptionCollection(Opus.Core.IModule module, Opus.Core.Target target)
        {
            var compilerOptions = module.Options as C.ICCompilerOptions;
            compilerOptions.ShowIncludes = true;
            compilerOptions.Defines.Add("DEFINE_FOR_ALL_SOURCE");
        }
    }

    sealed class BuildTerminalApplicationFromC : C.Application
    {
        sealed class SourceFiles : C.ObjectFileCollection
        {
            public SourceFiles()
            {
                var sourceDir = this.PackageLocation.SubDirectory("source");
                this.Include(sourceDir, "main.c");
            }
        }

        [Opus.Core.SourceFiles]
        SourceFiles sourceFiles = new SourceFiles();

        [Opus.Core.DependentModules(Platform=Opus.Core.EPlatform.Windows, ToolsetTypes=new [] {typeof(VisualC.Toolset)})]
        Opus.Core.Array<System.Type> dependents = new Opus.Core.Array<System.Type>(typeof(WindowsSDK.WindowsSDK));

        [C.RequiredLibraries(Platform = Opus.Core.EPlatform.Windows, ToolsetTypes=new[] { typeof(VisualC.Toolset)})]
        Opus.Core.StringArray libraries = new Opus.Core.StringArray("KERNEL32.lib");
    }

    sealed class BuildTerminalApplicationFromCxx : C.Application
    {
        sealed class SourceFiles : C.Cxx.ObjectFileCollection
        {
            public SourceFiles()
            {
                var sourceDir = this.PackageLocation.SubDirectory("source");
                this.Include(sourceDir, "main.c");
            }
        }

        [Opus.Core.SourceFiles]
        SourceFiles sourceFiles = new SourceFiles();

        [Opus.Core.DependentModules(Platform=Opus.Core.EPlatform.Windows, ToolsetTypes=new[] {typeof(VisualC.Toolset)})]
        Opus.Core.Array<System.Type> dependents = new Opus.Core.Array<System.Type>(typeof(WindowsSDK.WindowsSDK));

        [C.RequiredLibraries(Platform = Opus.Core.EPlatform.Windows, ToolsetTypes=new[]{typeof(VisualC.Toolset)})]
        Opus.Core.StringArray libraries = new Opus.Core.StringArray("KERNEL32.lib");
    }

    sealed class BuildTerminalApplicationWithUpdatedOptions : C.Application
    {
        sealed class SourceFiles : C.ObjectFileCollection
        {
            public SourceFiles()
            {
                var sourceDir = this.PackageLocation.SubDirectory("source");
                this.Include(sourceDir, "main.c");

                this.UpdateOptions += OverrideOptionCollection;
            }

            private static void OverrideOptionCollection(Opus.Core.IModule module, Opus.Core.Target target)
            {
                var compilerOptions = module.Options as C.ICCompilerOptions;
                compilerOptions.ShowIncludes = true;
                compilerOptions.CharacterSet = C.ECharacterSet.NotSet;

                var vcOptions = compilerOptions as VisualC.CCompilerOptionCollection;
                if (null != vcOptions)
                {
                    //vcOptions.DebugType = VisualC.EDebugType.Embedded;
                }
                var mingwOptions = compilerOptions as Mingw.CCompilerOptionCollection;
                if (null != mingwOptions)
                {
                }
            }
        }

        [Opus.Core.SourceFiles]
        SourceFiles sourceFiles = new SourceFiles();

        [Opus.Core.DependentModules(Platform=Opus.Core.EPlatform.Windows, ToolsetTypes=new[]{typeof(VisualC.Toolset)})]
        Opus.Core.Array<System.Type> dependents = new Opus.Core.Array<System.Type>(typeof(WindowsSDK.WindowsSDK));

        [C.RequiredLibraries(Platform = Opus.Core.EPlatform.Windows, ToolsetTypes=new[]{typeof(VisualC.Toolset)})]
        Opus.Core.StringArray libraries = new Opus.Core.StringArray("KERNEL32.lib");
    }

    [Opus.Core.ModuleTargets(Platform=Opus.Core.EPlatform.Windows)]
    sealed class BuildWindowsApplication : C.WindowsApplication
    {
        sealed class SourceFiles : C.ObjectFileCollection
        {
            public SourceFiles()
            {
                var sourceDir = this.PackageLocation.SubDirectory("source");
                this.Include(sourceDir, "main.c");
                this.UpdateOptions += new Opus.Core.UpdateOptionCollectionDelegate(Clang_CompilerOptions);
            }

            void Clang_CompilerOptions(Opus.Core.IModule module, Opus.Core.Target target)
            {
                if (target.HasToolsetType(typeof(Clang.Toolset)))
                {
                    var cOptions = module.Options as C.ICCompilerOptions;
                    // Microsoft headers do not compile warning free with Clang
                    cOptions.WarningsAsErrors = false;
                }
            }
        }

        sealed class Win32ResourceFile : C.Win32Resource
        {
            public Win32ResourceFile()
            {
                var resourcesDir = this.PackageLocation.SubDirectory("resources");
                this.Include(resourcesDir, "win32.rc");
            }
        }

        [Opus.Core.SourceFiles]
        SourceFiles sourceFiles = new SourceFiles();

        [Opus.Core.DependentModules(ToolsetTypes=new[]{typeof(VisualC.Toolset)})]
        Opus.Core.TypeArray vcDependents = new Opus.Core.TypeArray(
            typeof(WindowsSDK.WindowsSDK)
            );

        [Opus.Core.DependentModules]
        Opus.Core.TypeArray mingwDependents = new Opus.Core.TypeArray(
            typeof(Win32ResourceFile)
            );

        [C.RequiredLibraries(ToolsetTypes=new[]{typeof(VisualC.Toolset)})]
        Opus.Core.StringArray libraries = new Opus.Core.StringArray("KERNEL32.lib");
    }
}
