#region License
// Copyright 2010-2014 Mark Final
//
// This file is part of BuildAMation.
//
// BuildAMation is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// BuildAMation is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with BuildAMation.  If not, see <http://www.gnu.org/licenses/>.
#endregion

[assembly: Bam.Core.RegisterAction(typeof(Bam.CreatePackageAtAction))]

namespace Bam
{
    [Core.TriggerAction]
    internal class CreatePackageAtAction :
        Core.IActionWithArguments
    {
        public string CommandLineSwitch
        {
            get
            {
                return "-createpackageat";
            }
        }

        public string Description
        {
            get
            {
                return "Create a new package at the specified path.";
            }
        }

        void
        Core.IActionWithArguments.AssignArguments(
            string arguments)
        {
            this.PackagePath = arguments;
        }

        private string PackagePath
        {
            get;
            set;
        }

        public bool
        Execute()
        {
            bool isWellDefined;
            var id = Core.PackageUtilities.IsPackageDirectory(this.PackagePath, out isWellDefined);
            if ((null != id) || isWellDefined)
            {
                throw new Core.Exception("Package already present at '{0}'", this.PackagePath);
            }

            var PackageDirectory = this.PackagePath;
            if (System.IO.Directory.Exists(PackageDirectory))
            {
                Core.Log.Info("Package directory already exists at '{0}'", PackageDirectory);
                return false;
            }
            else
            {
                System.IO.Directory.CreateDirectory(PackageDirectory);
            }

            id = Core.PackageUtilities.IsPackageDirectory(this.PackagePath, out isWellDefined);

            // Xml file for dependencies
            var packageDefinition = new Core.PackageDefinitionFile(id.DefinitionPathName, true);
            if (null == packageDefinition)
            {
                throw new Core.Exception("Package definition file '%s' could not be created", packageDefinition);
            }

            if (Core.State.PackageCreationDependents != null)
            {
                Core.Log.DebugMessage("Adding dependent packages:");
                foreach (var dependentPackage in Core.State.PackageCreationDependents)
                {
                    Core.Log.DebugMessage("\t'{0}'", dependentPackage);
                    var packageNameAndVersion = dependentPackage.Split('-');
                    if (packageNameAndVersion.Length != 2)
                    {
                        throw new Core.Exception("Ill-formed package name-version pair, '{0}'", packageNameAndVersion);
                    }

                    var idToAdd = new Core.PackageIdentifier(packageNameAndVersion[0], packageNameAndVersion[1]);
                    packageDefinition.AddRequiredPackage(idToAdd);
                }
            }
            packageDefinition.OpusAssemblies.Add("Bam.Core");
            {
                var system = new Core.DotNetAssemblyDescription("System");
                system.RequiredTargetFramework = "2.0.50727";
                packageDefinition.DotNetAssemblies.Add(system);

                var systemXml = new Core.DotNetAssemblyDescription("System.Xml");
                systemXml.RequiredTargetFramework = "2.0.50727";
                packageDefinition.DotNetAssemblies.Add(systemXml);
            }
            packageDefinition.Write();
            id.Definition = packageDefinition;

            // Script file
            var packageScriptPathname = id.ScriptPathName;
            using (var scriptWriter = new System.IO.StreamWriter(packageScriptPathname))
            {
                scriptWriter.WriteLine("// Automatically generated by BuildAMation v" + Core.State.VersionString);
                scriptWriter.WriteLine("namespace " + id.Name);
                scriptWriter.WriteLine("{");
                scriptWriter.WriteLine("}");
                scriptWriter.Close();
            }

            Core.Log.Info("Successfully created package '{0}' in '{1}'", id.ToString("-"), id.Root.AbsolutePath);

            return true;
        }

        #region ICloneable Members

        object
        System.ICloneable.Clone()
        {
            return this.MemberwiseClone();
        }

        #endregion
    }
}