#!/bin/bash

curPath=$(dirname ${BASH_SOURCE[0]})

if [ "$OSTYPE" == "msys" ] || [ "$OSTYPE" == "cygwin" ]; then

exec $curPath/bam.exe $@

else

# need to call mono with --debug in order to get proper line numbers etc. when an exception is thrown
case $* in
*-debugsymbols*) monoargs=--debug;;
esac

exec mono $monoargs $curPath/bam.exe $@

fi
