#!/bin/bash

curPath=$(dirname ${BASH_SOURCE[0]})

if [ "$OSTYPE" == "msys" ] || [ "$OSTYPE" == "cygwin" ]; then

exec $curPath/bam.exe $@

else

# save the original (quoted) args
args=$@

# need to call mono with --debug in order to get proper line numbers etc. when an exception is thrown
while [ "$1" != "" ]; do
    case $1 in
        --debug | -d) monoargs=--debug;;
        #*) monoargs=-O=all;; # experimental
    esac
    shift
done

#echo mono $monoargs $curPath/bam.exe $args
exec mono $monoargs $curPath/bam.exe $args

fi
