@ECHO OFF

FOR /D %%A IN (%CD%\*) DO CALL :FIND_PACKAGE_VERSIONS %%A
PAUSE
GOTO :EOF

:FIND_PACKAGE_VERSIONS
FOR /D %%B IN (%1\*) DO CALL :DELETE_OPUS_DIRECTORIES %%B
GOTO :EOF

:DELETE_OPUS_DIRECTORIES
IF EXIST %1\Opus (
    ECHO Deleting '%1\Opus' directory and all children
    RMDIR /S /Q %1\Opus
)
GOTO :EOF
