// Automatically generated by Opus v0.00
namespace CSharpTest1
{
    // Define module classes here
    class SimpleLibrary :
        CSharp.Library
    {
        public
        SimpleLibrary()
        {
            var sourceDir = this.PackageLocation.SubDirectory("source");
            this.source.Include(sourceDir, "simpletest.cs");
        }

        [Opus.Core.SourceFiles]
        Opus.Core.FileCollection source = new Opus.Core.FileCollection();

#if OPUSPACKAGE_PUBLISHER_DEV
        [Publisher.CopyFileLocations]
        Opus.Core.Array<Publisher.PublishDependency> publishKeys = new Opus.Core.Array<Publisher.PublishDependency>(
            new Publisher.PublishDependency(CSharp.Assembly.OutputFile));
#endif
    }

    class SimpleExecutable :
        CSharp.Executable
    {
        public
        SimpleExecutable()
        {
            var sourceDir = this.PackageLocation.SubDirectory("source");
            this.source = Opus.Core.FileLocation.Get(sourceDir, "simpleexecutable.cs");
        }

        [Opus.Core.SourceFiles]
        Opus.Core.Location source;
    }

    class SimpleWindowExecutable :
        CSharp.WindowsExecutable
    {
        public
        SimpleWindowExecutable()
        {
            var sourceDir = this.PackageLocation.SubDirectory("source");
            this.source = Opus.Core.FileLocation.Get(sourceDir, "simplewindowsexecutable.cs");
        }

        [Opus.Core.SourceFiles]
        Opus.Core.Location source;
    }

    // disabled on Unix builds, as it fails: CS0016
    // Could not write to file `SimpleModule', cause: fileName '<blah>' must not include a path.
    [Opus.Core.ModuleTargets(Platform=Opus.Core.EPlatform.NotUnix)]
    class SimpleModule :
        CSharp.Module
    {
        public
        SimpleModule()
        {
            var sourceDir = this.PackageLocation.SubDirectory("source");
            this.source = Opus.Core.FileLocation.Get(sourceDir, "simplemodule.cs");
        }

        [Opus.Core.SourceFiles]
        Opus.Core.Location source;
    }

    class Executable2 :
        CSharp.Executable
    {
        public
        Executable2()
        {
            var sourceDir = this.PackageLocation.SubDirectory("source");
            this.source = Opus.Core.FileLocation.Get(sourceDir, "executable2.cs");
        }

        [Opus.Core.SourceFiles]
        Opus.Core.Location source;

        [Opus.Core.DependentModules]
        Opus.Core.TypeArray dependents = new Opus.Core.TypeArray(typeof(SimpleLibrary));

#if OPUSPACKAGE_PUBLISHER_DEV
        [Publisher.CopyFileLocations]
        Opus.Core.Array<Publisher.PublishDependency> publishKeys = new Opus.Core.Array<Publisher.PublishDependency>(
            new Publisher.PublishDependency(CSharp.Assembly.OutputFile));
#endif
    }

#if OPUSPACKAGE_PUBLISHER_DEV
    class Publish :
        Publisher.ProductModule
    {
        [Publisher.PrimaryTarget]
        System.Type primary = typeof(Executable2);
    }
#endif

    class ExecutableReferences :
        CSharp.Executable
    {
        public
        ExecutableReferences()
        {
            var sourceDir = this.PackageLocation.SubDirectory("source");
            this.source = Opus.Core.FileLocation.Get(sourceDir, "executablexml.cs");

            this.UpdateOptions += new Opus.Core.UpdateOptionCollectionDelegate(ExecutableReferences_UpdateOptions);
        }

        void
        ExecutableReferences_UpdateOptions(
            Opus.Core.IModule module,
            Opus.Core.Target target)
        {
            var options = module.Options as CSharp.IOptions;
            options.References.Add("System.Xml.dll");
        }

        [Opus.Core.SourceFiles]
        Opus.Core.Location source;
    }
}
