// Automatically generated by Opus v0.00
namespace Test6
{
    // Define module classes here
    class ConditionalApplication : C.Application
    {
        // TODO: derive C.SourceFiles from this attribute?
        [Opus.Core.SourceFiles]
        private SourceFiles sourceFiles;

        public ConditionalApplication(Opus.Core.Target target)
        {
            this.sourceFiles = new SourceFiles(target);
            this.UpdateOptions += this.OverrideOptionCollection;
        }

        class SourceFiles : C.ObjectFileCollection
        {
            public SourceFiles(Opus.Core.Target target)
            {
                this.UpdateOptions += this.OverrideOptionCollection;

                C.ObjectFile mainObjectFile = new C.ObjectFile();
                mainObjectFile.SetRelativePath(this, "source", "main.c");
                mainObjectFile.UpdateOptions += MainUpdateOptionCollection;
                this.Add(mainObjectFile);

                if (target.HasConfiguration(Opus.Core.EConfiguration.Debug))
                {
                    this.Include(this, "source", "debug", "debug.c");
                }
                else
                {
                    this.Include(this, "source", "optimized", "optimized.c");
                }
            }

            private void OverrideOptionCollection(Opus.Core.IModule module, Opus.Core.Target target)
            {
                C.ICCompilerOptions compilerOptions = module.Options as C.ICCompilerOptions;
                compilerOptions.IncludePaths.Include(this, "include");
            }

            private void MainUpdateOptionCollection(Opus.Core.IModule module, Opus.Core.Target target)
            {
                C.ICCompilerOptions compilerOptions = module.Options as C.ICCompilerOptions;
                compilerOptions.Defines.Add("MAIN_C");
                compilerOptions.IncludePaths.Include(this, "include", "platform");
            }
        }

        private void OverrideOptionCollection(Opus.Core.IModule module, Opus.Core.Target target)
        {
            C.ILinkerOptions options = module.Options as C.ILinkerOptions;
            //options.DebugSymbols = false;
        }

        [Opus.Core.DependentModules(Platform=Opus.Core.EPlatform.Windows, Toolchains=new string[] {"visualc"})]
        Opus.Core.TypeArray winVCDependents = new Opus.Core.TypeArray(typeof(WindowsSDK.WindowsSDK));

        [C.RequiredLibraries(Platform = Opus.Core.EPlatform.Windows, Toolchains = new string[] { "visualc" })]
        Opus.Core.StringArray libraries = new Opus.Core.StringArray("KERNEL32.lib");
    }
}
