// Automatically generated by Opus v0.00
namespace Test6
{
    // Define module classes here
    class ConditionalApplication :
        C.Application
    {
        // TODO: derive C.SourceFiles from this attribute?
        [Bam.Core.SourceFiles]
        private SourceFiles sourceFiles;

        public
        ConditionalApplication(
            Bam.Core.Target target)
        {
            this.sourceFiles = new SourceFiles(target);
            this.UpdateOptions += this.OverrideOptionCollection;
        }

        class SourceFiles :
            C.ObjectFileCollection
        {
            public
            SourceFiles(
                Bam.Core.Target target)
            {
                this.UpdateOptions += this.OverrideOptionCollection;

                var sourceDir = this.PackageLocation.SubDirectory("source");
                var debugSourceDir = sourceDir.SubDirectory("debug");
                var optSourceDir = sourceDir.SubDirectory("optimized");

                var mainObjectFile = new C.ObjectFile();
                mainObjectFile.Include(sourceDir, "main.c");
                mainObjectFile.UpdateOptions += MainUpdateOptionCollection;
                this.Add(mainObjectFile);

                if (target.HasConfiguration(Bam.Core.EConfiguration.Debug))
                {
                    this.Include(debugSourceDir, "debug.c");
                }
                else
                {
                    this.Include(optSourceDir, "optimized.c");
                }
            }

            private void
            OverrideOptionCollection(
                Bam.Core.IModule module,
                Bam.Core.Target target)
            {
                var compilerOptions = module.Options as C.ICCompilerOptions;
                compilerOptions.IncludePaths.Include(this.PackageLocation.SubDirectory("include"));
            }

            private void
            MainUpdateOptionCollection(
                Bam.Core.IModule module,
                Bam.Core.Target target)
            {
                var compilerOptions = module.Options as C.ICCompilerOptions;
                compilerOptions.Defines.Add("MAIN_C");
                var includeDir = this.PackageLocation.SubDirectory("include");
                compilerOptions.IncludePaths.Include(includeDir, "platform");
            }
        }

        private void
        OverrideOptionCollection(
            Bam.Core.IModule module,
            Bam.Core.Target target)
        {
            //var options = module.Options as C.ILinkerOptions;
            //options.DebugSymbols = false;
        }

        [Bam.Core.DependentModules(Platform = Bam.Core.EPlatform.Windows, ToolsetTypes = new[] { typeof(VisualC.Toolset) })]
        Bam.Core.TypeArray winVCDependents = new Bam.Core.TypeArray(typeof(WindowsSDK.WindowsSDK));

        [C.RequiredLibraries(Platform = Bam.Core.EPlatform.Windows, ToolsetTypes = new[] { typeof(VisualC.Toolset) })]
        Bam.Core.StringArray libraries = new Bam.Core.StringArray("KERNEL32.lib");
    }
}
