#!/bin/bash

# need to call mono with --debug in order to get proper line numbers etc. when an exception is thrown
case $* in
*-debugsymbols*) monoargs=--debug;;
esac

exec mono $monoargs $OPUSPATH/Opus.exe $@

