// Automatically generated by Opus v0.00
namespace Test8
{
    // Define module classes here

    [Opus.Core.ModuleTargets(new string[] { "win.*-.*-.*" })]
    class ApplicationTest : C.Application
    {
        private const string WinVCTarget = "win.*-.*-visualc";

        public ApplicationTest()
        {
            this.sourceFile.SetRelativePath(this, "source", "main.c");
        }

        [Opus.Core.SourceFiles]
        C.ObjectFile sourceFile = new C.ObjectFile();

        [Opus.Core.RequiredModules]
        Opus.Core.TypeArray requiredModules = new Opus.Core.TypeArray(
            typeof(Test7.ExplicitDynamicLibrary)
        );

        [Opus.Core.DependentModules(WinVCTarget)]
        Opus.Core.TypeArray winVCDependents = new Opus.Core.TypeArray(
            typeof(WindowsSDK.WindowsSDK)
        );

        [C.RequiredLibraries(WinVCTarget)]
        Opus.Core.StringArray libraries = new Opus.Core.StringArray(
            "KERNEL32.lib",
            "dbghelp.lib"
        );
    }

    [Opus.Core.ModuleTargets(new string[] { "win.*-.*-.*" })]
    class PublishDynamicLibraries : FileUtilities.CopyFiles
    {
        [FileUtilities.SourceModules(C.OutputFileFlags.Executable)]
        Opus.Core.TypeArray sourceTargets = new Opus.Core.TypeArray(typeof(Test7.ExplicitDynamicLibrary));

        [FileUtilities.DestinationModuleDirectory(C.OutputFileFlags.Executable)]
        Opus.Core.TypeArray destinationTarget = new Opus.Core.TypeArray(typeof(ApplicationTest));
    }
}
