// <copyright file="CreatePackageAction.cs" company="Mark Final">
//  Opus
// </copyright>
// <summary>Opus main application.</summary>
// <author>Mark Final</author>

[assembly: Opus.Core.RegisterAction(typeof(Opus.CreatePackageAction))]

namespace Opus
{
    [Core.TriggerAction]
    internal class CreatePackageAction : Core.IActionWithArguments
    {
        public string CommandLineSwitch
        {
            get
            {
                return "-createpackage";
            }
        }

        public string Description
        {
            get
            {
                return "Create a new package";
            }
        }

        public void AssignArguments(string arguments)
        {
            this.PackagePath = arguments;
        }

        private string PackagePath
        {
            get;
            set;
        }

        public bool Execute()
        {
            Core.PackageInformation createPackage = Core.PackageInformation.FromPath(this.PackagePath, false);
            if (null == createPackage)
            {
                throw new Core.Exception(System.String.Format("Path '{0}' is not a valid package path", this.PackagePath), false);
            }

            Core.PackageInformationCollection packageInfoCollection = Core.State.PackageInfo;
            if (null == packageInfoCollection)
            {
                packageInfoCollection = new Opus.Core.PackageInformationCollection();
                Core.State.PackageInfo = packageInfoCollection;
            }

            packageInfoCollection.Add(createPackage);

            Core.Log.DebugMessage("Package is '{0}-{1}' @ '{2}", createPackage.Name, createPackage.Version, createPackage.Root);
            Core.Log.DebugMessage("Package roots are:");
            foreach (string packageRoot in Core.State.PackageRoots)
            {
                Core.Log.DebugMessage("\t'{0}'", packageRoot);
            }

            string PackageDirectory = createPackage.Directory;
            if (System.IO.Directory.Exists(PackageDirectory))
            {
                Core.Log.Info("Package '{0}-{1}' already exists at '{2}'",
                              createPackage.Name, createPackage.Version,
                              createPackage.Root);
                return false;
            }
            else
            {
                System.IO.Directory.CreateDirectory(PackageDirectory);
            }

            // Xml file for dependencies
            string packageDependencyXmlPathname = createPackage.DependencyFile;
            string opusSchemaPathname = Core.State.OpusPackageDependencySchemaPathName;
            Core.PackageDependencyXmlFile packageDependencyXmlFile = new Core.PackageDependencyXmlFile(packageDependencyXmlPathname, opusSchemaPathname, true);
            if (Core.State.PackageCreationDependents != null)
            {
                Core.Log.DebugMessage("Adding dependent packages:");
                foreach (string dependentPackage in Core.State.PackageCreationDependents)
                {
                    Core.Log.DebugMessage("\t'{0}'", dependentPackage);
                    string[] packageNameAndVersion = dependentPackage.Split('-');
                    if (packageNameAndVersion.Length != 2)
                    {
                        throw new Core.Exception(System.String.Format("Ill-formed package name-version pair, '{0}'", packageNameAndVersion), false);
                    }

                    packageDependencyXmlFile.AddRequiredPackage(packageNameAndVersion[0], packageNameAndVersion[1]);
                }
            }
            packageDependencyXmlFile.Write();

            // Script file
            string packageScriptPathname = createPackage.ScriptFile;
            using (System.IO.TextWriter scriptWriter = new System.IO.StreamWriter(packageScriptPathname))
            {
                scriptWriter.WriteLine("// Automatically generated by Opus v" + Core.State.OpusVersionString);
                scriptWriter.WriteLine("namespace " + createPackage.Name);
                scriptWriter.WriteLine("{");
                scriptWriter.WriteLine("    // Define module classes here");
                scriptWriter.WriteLine("}");
                scriptWriter.Close();
            }

            Core.Log.Info("Successfully created package '{0}-{1}' at '{2}", createPackage.Name, createPackage.Version, PackageDirectory);

            return true;
        }
    }
}