// <copyright file="XCodeBuilder.cs" company="Mark Final">
//  Opus package
// </copyright>
// <summary>XCodeBuilder package</summary>
// <author>Mark Final</author>

[assembly: Opus.Core.DeclareBuilder("Xcode", typeof(XCodeBuilder.XCodeBuilder))]

// Automatically generated by Opus v 0.50
namespace XCodeBuilder
{
}
