// <copyright file="XcodeBuilder.cs" company="Mark Final">
//  Opus package
// </copyright>
// <summary>XcodeBuilder package</summary>
// <author>Mark Final</author>

[assembly: Bam.Core.DeclareBuilder("Xcode", typeof(XcodeBuilder.XcodeBuilder))]

// Automatically generated by Opus v 0.50
namespace XcodeBuilder
{
}
