// Automatically generated by Opus v0.50
namespace HeaderLibraryTest
{
    class HeaderLibrary : C.HeaderLibrary
    {
        public HeaderLibrary()
        {
            this.headers.Include(this.PackageLocation, "include", "*.h");

            this.UpdateOptions += new Opus.Core.UpdateOptionCollectionDelegate(HeaderLibrary_IncludePaths);
        }

        [C.ExportCompilerOptionsDelegate]
        void HeaderLibrary_IncludePaths(Opus.Core.IModule module, Opus.Core.Target target)
        {
            var options = module.Options as C.ICCompilerOptions;
            options.IncludePaths.Include(this.PackageLocation, "include");
            var c = module.Options as GccCommon.ICCompilerOptions;
            c.Pedantic = false;
        }

        [C.HeaderFiles]
        Opus.Core.FileCollection headers = new Opus.Core.FileCollection();
    }

    class Application : C.Application
    {
        public Application()
        {
            this.sourceFile.Include(this.PackageLocation, "source", "main.c");
        }

        [Opus.Core.SourceFiles]
        C.Cxx.ObjectFile sourceFile = new C.Cxx.ObjectFile();

        [Opus.Core.DependentModules]
        Opus.Core.TypeArray dependents = new Opus.Core.TypeArray(
            typeof(HeaderLibrary)
            );
    }
}
