// Automatically generated by Opus v0.50
[assembly: C.RegisterToolchain(
    "clang",
    typeof(Clang.ToolsetInfo),
    typeof(Clang.CCompiler), typeof(Clang.CCompilerOptionCollection),
    typeof(Clang.CxxCompiler), typeof(Clang.CxxCompilerOptionCollection),
    null, null,
    null, null,
    null, null)]

namespace Clang
{
    // Add modules here
    public class ToolsetInfo : Opus.Core.IToolsetInfo
    {
        string Opus.Core.IToolsetInfo.Version(Opus.Core.Target target)
        {
            return "3.1";
        }

        string Opus.Core.IToolsetInfo.InstallPath(Opus.Core.Target target)
        {
            return @"D:\dev\Thirdparty\Clang\3.1\build\bin\Release";
        }
    }
}
