// Automatically generated by Opus v0.00
namespace MixedModeCpp
{
    // Define module classes here
    [Bam.Core.ModuleTargets(Platform = Bam.Core.EPlatform.Windows, ToolsetTypes = new[] { typeof(VisualC.Toolset) })]
    class TestApplication :
        C.Application
    {
        public
        TestApplication()
        {
            this.UpdateOptions += new Bam.Core.UpdateOptionCollectionDelegate(TestApplication_UpdateOptions);
        }

        void
        TestApplication_UpdateOptions(
            Bam.Core.IModule module,
            Bam.Core.Target target)
        {
            var options = module.Options as C.ILinkerOptions;
            options.DoNotAutoIncludeStandardLibraries = false;
        }

        class SourceFiles :
            C.Cxx.ObjectFileCollection
        {
            public
            SourceFiles()
            {
                var sourceDir = this.PackageLocation.SubDirectory("source");
                this.Include(sourceDir, "native.cpp");
            }
        }

        class ManagedSourceFiles :
            VisualCCommon.ManagedCxxObjectFileCollection
        {
            public
            ManagedSourceFiles()
            {
                var sourceDir = this.PackageLocation.SubDirectory("source");
                this.Include(sourceDir, "managed.cpp");
            }
        }

        [Bam.Core.SourceFiles]
        SourceFiles nativeSourceFiles = new SourceFiles();

        [Bam.Core.SourceFiles]
        ManagedSourceFiles managedSourceFiles = new ManagedSourceFiles();

        [Bam.Core.DependentModules]
        Bam.Core.TypeArray dependentModules = new Bam.Core.TypeArray(
            typeof(WindowsSDK.WindowsSDK)
        );

        [C.RequiredLibraries]
        Bam.Core.StringArray libraries = new Bam.Core.StringArray(
            "KERNEL32.lib",
            "mscoree.lib"
        );
    }
}
