// Automatically generated by Opus v0.00
namespace Test12
{
    // Define module classes here
    class MyOpenGLApplication : C.WindowsApplication
    {
        private const string WinTarget = "win.*-.*-.*";
        private const string UnixTarget = "unix.*-.*-.*";
        private const string WinVCTarget = "win.*-.*-visualc";

        class CommonSourceFiles : C.CPlusPlus.ObjectFileCollection
        {
            public CommonSourceFiles()
            {
                this.AddRelativePaths(this, "source", "main.cpp");
            }
        }

        class WindowsSourceFiles : C.CPlusPlus.ObjectFileCollection
        {
            public WindowsSourceFiles()
            {
                this.AddRelativePaths(this, "source", "win", "win.cpp");
            }
        }

        class UnixSourceFiles : C.CPlusPlus.ObjectFileCollection
        {
            public UnixSourceFiles()
            {
                this.AddRelativePaths(this, "source", "unix", "unix.cpp");
            }
        }

        [Opus.Core.SourceFiles]
        CommonSourceFiles commonSourceFiles = new CommonSourceFiles();
        [Opus.Core.SourceFiles(WinTarget)]
        WindowsSourceFiles windowsSourceFiles = new WindowsSourceFiles();
        [Opus.Core.SourceFiles(UnixTarget)]
        UnixSourceFiles unixSourceFiles = new UnixSourceFiles();

        [Opus.Core.DependentModules(WinVCTarget)]
        Opus.Core.TypeArray windowsVCDependents = new Opus.Core.TypeArray(
            typeof(WindowsSDK.WindowsSDK)
        );

        [C.RequiredLibraries(WinVCTarget)]
        Opus.Core.StringArray windowsVCLibraries = new Opus.Core.StringArray(
            "KERNEL32.lib",
            "USER32.lib"
        );

        [C.RequiredLibraries(UnixTarget)]
        Opus.Core.StringArray unixLibraries = new Opus.Core.StringArray(
            "-lX11"
        );
    }
}
